### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by MaraBytes** [rahul7400/OnlineAuctionApp#2]
The app crashes as soon as build is completed and launched on my device

**Comment by rahul7400** [comment]
Can u send the screenshot of the error you getting in android studio

**Comment by Oyopiz** [comment]
![Uploading rahul error.png…]()

**Comment by MaraBytes** [comment]
![rahul error](https://user-images.githubusercontent.com/56676343/132124597-9b1126b8-1991-40fd-9482-ce100885cc12.png)
![rahul error 2](https://user-images.githubusercontent.com/56676343/132124602-ed446b1f-8356-429a-b5f8-bc44fe6916fa.png)

**Comment by MaraBytes** [comment]
The second image is the referenced line in the error on first image

**Comment by rahul7400** [comment]
Bro have initialized your own firebase project into the app?

**Comment by MaraBytes** [comment]
Oh! .How do I do that? Do I need to replace the google.json file with my own json file? and if so what else do I need to change?

**Comment by rahul7400** [comment]
Yes u are currently trying to view my data which is giving u some kind of error just replace the google.json file with yours and enable the email and password auth from firebase and enable the realtime database as well and then i think it should work perfectly fine .

**Comment by Pranay2709** [comment]
How can I contact you ? Your Instagram or any thing else ?  I am working on this project by using your code for my collage project. Can you help me ?
